import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css']
})
export class NavigationComponent implements OnInit {
  private cash_expenses = [
    {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    },
    {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }, {
      Srno: 1,
      Desc: "hi",
      Deposit: 30,
      Withdraw: 40
    }
  ];
  constructor() { }

  ngOnInit() {
  }

}
